{
 "title": "OCI Metrics Dashboard",
 "description": "View Monitoring Metrics by Compartment and Region",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "compartment", "query": "compartments()" },
   { "name": "region", "label": "Region", "query": "regions()" }
  ]
 },
 "panels": [
  {
   "title": "CPU Utilization",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "Utilization Percentage" }
   ],
   "targets": [
    {
     "aggregation": "mean()",
     "compartment": "$compartment",
     "metric": "CpuUtilization",
     "namespace": "oci_computeagent",
     "region": "$region",
     "resolution": "1m",
     "window": "1m"
    }
   ]
  },
  {
   "title": "Memory Utilization",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "Average Percentage Utilized" }
   ],
   "targets": [
    {
     "aggregation": "mean()",
     "compartment": "$compartment",
     "metric": "MemoryUtilization",
     "namespace": "oci_computeagent",
     "region": "$region",
     "resolution": "1m",
     "window": "1m"
    }
   ]
  },
  {
   "title": "Block Volumes",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short", "label": "Activity" }
   ],
   "targets": [
    {
     "aggregation": "mean()",
     "compartment": "$compartment",
     "metric": "VolumeReadOps",
     "namespace": "oci_blockstore",
     "region": "$region",
     "resolution": "1m",
     "tags": [
      { "key": "attachmentId", "operator": "=", "value": "select tag value" }
     ],
     "window": "1m"
    },
    {
     "aggregation": "mean()",
     "compartment": "$compartment",
     "metric": "VolumeWriteOps",
     "namespace": "oci_blockstore",
     "region": "$region",
     "resolution": "1m",
     "window": "1m"
    }
   ]
  },
  {
   "title": "Load Balancers",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short", "label": "Activity" }
   ],
   "targets": [
    {
     "aggregation": "percentile(.95)",
     "compartment": "$compartment",
     "metric": "AcceptedConnections",
     "namespace": "oci_lbaas",
     "region": "$region",
     "resolution": "1m",
     "tags": [
      { "key": "availabilityDomain", "operator": "=", "value": "iad-ad-1" }
     ],
     "window": "1m"
    },
    {
     "aggregation": "mean()",
     "compartment": "$compartment",
     "metric": "HttpRequests",
     "namespace": "oci_lbaas",
     "region": "$region",
     "resolution": "1m",
     "window": "1m"
    }
   ]
  }
 ]
}